import { db } from "./firebase-config.js";
import { ref,push,set,update,onValue,onDisconnect } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),room=params.get("room");
let studentId="",studentName="",board,ctx,teacher=null,tool="pen",color="#111827",size=4,zoom=1,startTime=Date.now(),drawing=false,sx=0,sy=0;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]));
function getOnce(path){return new Promise(resolve=>onValue(ref(db,path),s=>resolve(s.val()),{onlyOnce:true}))}
async function join(name){if(!room)return showError("Link inválido.");const c=await getOnce("classes/"+room);if(!c||c.status!=="live")return showError("Esta aula não está disponível.");studentName=name.trim();const p=push(ref(db,"participants/"+room));studentId=p.key;await set(p,{name:studentName,online:true,joinedAt:Date.now()});onDisconnect(ref(db,"participants/"+room+"/"+studentId+"/online")).set(false);teacher=await getOnce("teachers/"+c.teacherId);$("joinScreen").classList.add("hidden");$("classApp").classList.remove("hidden");$("classTeacher").textContent=teacher?.name||"Professor";$("classCourse").textContent=teacher?.courseName||c.title;startTime=c.startedAt||Date.now();setupBoard();setupTools();bindBoard();watchAll();setInterval(()=>{const s=Math.floor((Date.now()-startTime)/1000);$("timer").textContent=String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")},1000)}
function showError(x){$("joinError").textContent=x}
function setupBoard(){board=$("board");ctx=board.getContext("2d");resize();window.addEventListener("resize",resize)}
function resize(){const r=$("boardWrap").getBoundingClientRect();board.width=Math.max(300,r.width);board.height=Math.max(300,r.height);redraw()}
function redraw(){ctx.fillStyle="#fff";ctx.fillRect(0,0,board.width,board.height);onValue(ref(db,"whiteboards/"+room+"/objects"),s=>{const d=s.val()||{};Object.values(d).forEach(renderObject)},{onlyOnce:true})}
function renderObject(o){ctx.save();if(o.type==="stroke"){ctx.strokeStyle=o.color;ctx.lineWidth=o.size;ctx.lineCap="round";ctx.beginPath();o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else if(o.type==="line"){ctx.strokeStyle=o.color;ctx.lineWidth=o.size;ctx.beginPath();ctx.moveTo(o.a.x,o.a.y);ctx.lineTo(o.b.x,o.b.y);ctx.stroke()}else if(o.type==="rect"){ctx.strokeStyle=o.color;ctx.lineWidth=o.size;ctx.strokeRect(o.a.x,o.a.y,o.b.x-o.a.x,o.b.y-o.a.y)}else if(o.type==="text"){ctx.fillStyle=o.color;ctx.font="24px sans-serif";ctx.fillText(o.text,o.x,o.y)}ctx.restore()}
function point(e){const r=board.getBoundingClientRect();return{x:(e.clientX-r.left)*board.width/r.width,y:(e.clientY-r.top)*board.height/r.height}}
function add(o){return set(push(ref(db,"whiteboards/"+room+"/objects")),o)}
function bindBoard(){board.onpointerdown=e=>{const p=point(e);if(tool==="text"){const text=prompt("Texto:");if(text)add({type:"text",x:p.x,y:p.y,text,color});return}drawing=true;sx=p.x;sy=p.y};board.onpointerup=async e=>{if(!drawing)return;drawing=false;const p=point(e);if(tool==="pen"||tool==="eraser")await add({type:"stroke",points:[{x:sx,y:sy},{x:p.x,y:p.y}],color:tool==="eraser"?"#fff":color,size:tool==="eraser"?Math.max(size*3,12):size});else if(tool==="line"||tool==="rect")await add({type:tool,a:{x:sx,y:sy},b:p,color,size})};board.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.save();ctx.strokeStyle=tool==="eraser"?"#fff":color;ctx.lineWidth=tool==="eraser"?size*3:size;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();sx=p.x;sy=p.y}}
function setupTools(){document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{tool=b.dataset.tool;if(tool==="clear"){if(confirm("Limpar o quadro para todos?"))set(ref(db,"whiteboards/"+room+"/objects"),null);return}document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b))});document.querySelectorAll("[data-color]").forEach(b=>b.onclick=()=>color=b.dataset.color);$("brushSize").oninput=e=>size=+e.target.value;$("fullscreen").onclick=()=>document.documentElement.requestFullscreen?.();$("saveBoard").onclick=()=>{const a=document.createElement("a");a.download="quadro-"+room+".png";a.href=board.toDataURL();a.click()};$("zoomIn").onclick=()=>setZoom(zoom+.1);$("zoomOut").onclick=()=>setZoom(zoom-.1);$("fitBoard").onclick=()=>setZoom(1);$("raiseHand").onclick=()=>update(ref(db,"participants/"+room+"/"+studentId),{hand:true,handAt:Date.now()})}
function setZoom(z){zoom=Math.max(.5,Math.min(2,z));$("zoomValue").textContent=Math.round(zoom*100)+"%";board.style.transform="scale("+zoom+")"}
function watchBoard(){onValue(ref(db,"whiteboards/"+room+"/objects"),s=>{ctx.fillStyle="#fff";ctx.fillRect(0,0,board.width,board.height);Object.values(s.val()||{}).forEach(renderObject)})}
function watchParticipants(){onValue(ref(db,"participants/"+room),s=>{const a=Object.values(s.val()||{}).filter(x=>x.online!==false);$("participantCount").textContent=a.length;$("participantBadge").textContent=a.length+" participantes";$("participants").innerHTML=a.map(p=>"<div class='participant'><span class='avatar-sm'>"+esc((p.name||"A").charAt(0).toUpperCase())+"</span><span>"+esc(p.name)+"</span><span class='online'></span></div>").join("")})}
function watchChat(){onValue(ref(db,"messages/"+room),s=>{const d=s.val()||{};$("chatMessages").innerHTML=Object.values(d).map(m=>"<div class='message'><div class='msg-name'>"+esc(m.name)+"</div><div class='msg-text'>"+esc(m.text)+"</div></div>").join("");$("chatMessages").scrollTop=$("chatMessages").scrollHeight})}
function watchAll(){watchBoard();watchParticipants();watchChat()}
$("joinForm").addEventListener("submit",e=>{e.preventDefault();join($("studentName").value)});
$("chatForm").addEventListener("submit",async e=>{e.preventDefault();const t=$("chatInput").value.trim();if(t){await set(push(ref(db,"messages/"+room)),{name:studentName,text:t,time:Date.now()});$("chatInput").value=""}});
(async()=>{if(room){const c=await getOnce("classes/"+room);if(c){const t=await getOnce("teachers/"+c.teacherId);$("joinTeacher").textContent=t?.name||"QUADRO-AZNY";$("joinCourse").textContent=t?.courseName||c.title;$("joinTitle").textContent=c.title||"Entrar na aula"}}})();