import { db } from "./firebase-config.js";
import { ref, push, set, onValue } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
let teacherId=params.get("teacher")||localStorage.getItem("qaz_teacher_id"),currentTeacher=null,currentRoom=null;
async function saveTeacher(data){const r=push(ref(db,"teachers"));await set(r,{...data,createdAt:Date.now(),active:true});localStorage.setItem("qaz_teacher_id",r.key);return r.key}
function showTeacher(t){currentTeacher=t;$("setupScreen").classList.add("hidden");$("teacherApp").classList.remove("hidden");["headerTeacher","sideTeacher"].forEach(id=>$(id).textContent=t.name);["headerCourse","sideCourse"].forEach(id=>$(id).textContent=t.courseName||"Quadro Virtual");$("teacherAvatar").textContent=(t.name||"P").trim().charAt(0).toUpperCase()}
function classLink(room){return new URL("aula.html?room="+encodeURIComponent(room),location.href).href}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[c]))}
function watchStudents(room){onValue(ref(db,"participants/"+room),s=>{const d=s.val()||{},list=$("studentList");let n=0;list.innerHTML="";Object.values(d).forEach(p=>{if(p.online!==false){n++;const row=document.createElement("div");row.className="student-row";row.innerHTML="<span>"+esc(p.name||"Aluno")+"</span><span class='dot'></span>";list.appendChild(row)}});$("onlineCount").textContent=n;$("studentStat").textContent=n})}
async function startClass(){if(!currentTeacher)return alert("Configure primeiro o professor.");if(currentRoom)return location.href="aula.html?room="+currentRoom;const r=push(ref(db,"classes"));currentRoom=r.key;await set(r,{teacherId,title:currentTeacher.courseName||"Aula online",status:"live",createdAt:Date.now(),startedAt:Date.now(),accessCode:r.key});$("activeTitle").textContent=currentTeacher.courseName||"Aula online";$("activeRoom").textContent="Sala: "+r.key;$("classLink").value=classLink(r.key);$("linkArea").classList.remove("hidden");$("liveStatus").textContent="Aula em andamento";$("stateStat").textContent="Ao vivo";$("startClass").textContent="↗ Abrir Quadro";watchStudents(r.key)}
$("teacherForm")?.addEventListener("submit",async e=>{e.preventDefault();await saveTeacher({name:$("teacherName").value.trim(),courseName:$("courseName").value.trim(),whatsapp:$("teacherWhatsapp").value.trim(),photo:$("teacherPhoto").value.trim()});location.reload()});
$("startClass")?.addEventListener("click",startClass);
$("copyLink")?.addEventListener("click",async()=>{await navigator.clipboard.writeText($("classLink").value);$("copyLink").textContent="Copiado ✓";setTimeout(()=>$("copyLink").textContent="Copiar link",1500)});
$("waLink")?.addEventListener("click",()=>window.open("https://wa.me/?text="+encodeURIComponent("Entre na minha aula: "+$("classLink").value),"_blank"));
if(teacherId){onValue(ref(db,"teachers/"+teacherId),s=>{if(s.exists())showTeacher(s.val());else{teacherId=null;localStorage.removeItem("qaz_teacher_id")}});onValue(ref(db,"classes"),s=>{const all=s.val()||{};const mine=Object.values(all).filter(x=>x.teacherId===teacherId);$("classCount").textContent=mine.length})}